version: '3.8'  

services:  
  backend:  
    build: ./backend  
    command: gunicorn photoshare.wsgi:application --bind 0.0.0.0:8000  
    volumes:  
      - ./backend:/app  
      - media_volume:/app/media  
    ports:  
      - "8000:8000"  
    env_file:  
      - .env  
    depends_on:  
      - db  
      - redis  

  frontend:  
    build: ./frontend  
    ports:  
      - "3000:3000"  
    volumes:  
      - ./frontend:/app  
      - /app/node_modules  
    depends_on:  
      - backend  

  db:  
    image: postgres:15  
    environment:  
      POSTGRES_DB: photoshare  
      POSTGRES_USER: photoshare  
      POSTGRES_PASSWORD: securepassword  
    volumes:
      - pgdata:/var/lib/postgresql/data  

  redis:
    image: "redis:alpine"  

volumes:  
  pgdata:  
  media_volume:  